### ISSUE TITLE
ValueError: unconverted data remains: +08

### ISSUE THREAD

**Issue by kirajhpang** [CopOnTheRun/FB-Message-Parser#7]
Hi, I trying your project, still fresh in python, but I do install Anaconda and put `messenger.htm` as same directory, below is the output I get, any idea? 

```
Macbooks-MBP:FB-Message-Parser-master Kira$ python fb_parser.py 
/Users/macbook/anaconda/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 76 of the file fb_parser.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "fb_parser.py", line 76, in <module>
    chat = html_to_py(f)
  File "fb_parser.py", line 25, in html_to_py
    dt.strptime(y.find(class_='meta').string.replace("+01", ""), dtFormat),
  File "/Users/macbook/anaconda/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/Users/macbook/anaconda/lib/python3.6/_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: +08

```

**Comment by jsharkey13** [comment]
See #5, which is the same underlying problem! It's the timezone on the end of your timestamp that's causing the issue!
